---
title: "House_Price_Prediction"
author: "DANIAL ABEDI"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
#installing packeges
#install.packages(c("ggplot2","dplyr","scales"))
```




```{r}
#loading packages
library(dplyr)
library(ggplot2)
library(scales)

```

```{r}
#loading data
train_data <- read.csv("F:/Projects GitHub/house-prices-prediction/data/train.csv")
dim(train_data)
```
```{r}
#visualizing target variable(SalesPrice)

ggplot(train_data,aes(x=SalePrice )) +
  geom_histogram(fill= "steelblue",color = "white",bins=75) +
  theme_minimal() +
  labs(
    title = "Distribution of House Price in Ames",
    substitle = "Most houses are clustered around $100k - $200k ",
    x = "Sales Price",
    Y = "Number of Houses"
  ) +
  scale_x_continuous(
    breaks = c(100000,200000,400000,600000,800000),
    labels = comma)
```
```{r}
#Creating new column with the logarithmic transformation of SalePrice

train_data <- train_data %>%
  mutate(Log_SalePrice=log(SalePrice))
ggplot(train_data, aes(Log_SalePrice))+
  geom_histogram(fill="seagreen",color="white",bins = 75)+
  theme_minimal() +
  labs(
    title = " Log-Transformed Distribution of House Price" ,
    subtitle = " Using logarithm so that machine understand it better",
    x="Log(SalePrice)",
    y="Number of Houses"
  )
```
```{r}
#Cleaning Data 
train_data <- train_data %>%
  mutate(
    #here NA means the house doesn't have the mentioned facility
    PoolQC = ifelse(is.na(PoolQC), "None",PoolQC),
    MiscFeature=ifelse(is.na(MiscFeature),"None",MiscFeature),
    Alley=ifelse(is.na(Alley),"None",Alley),
    Fence=ifelse(is.na(Fence),"None", Fence),
    FireplaceQu=ifelse(is.na(FireplaceQu),"None",FireplaceQu),
    #using median to fill the following column
    LotFrontage=ifelse(is.na(LotFrontage),median(LotFrontage,na.rm = TRUE), LotFrontage)
  )
#test for NA(it is 0)

# print("Number of NA for PoolQC column after fixing")
# sum(is.na(train_data$PoolQC))
```


```{r}

#plotting the relationship between living area and house price
ggplot(train_data, aes(x=GrLivArea, y=Log_SalePrice))+
  geom_point(color = "darkblue",alpha=0.5)+
  #Add a straight trend line to show the overall direction
  # method = "lm" stands for Linear Model
  geom_smooth(method = "lm",color="red",se = FALSE)+
  theme_minimal()+
  labs(
    title = "Living Area vs. Log Sale Price",
    subtitle = "Notice the positive correlation: Bigger area = Higher price",
    x = "Above Ground Living Area (Square Feet)",
    y = "Logarithm of Sale Price"
  )
```


```{r}
#Removing outliers(very large, very cheap)
train_data<-train_data %>%
  filter(!(GrLivArea>4000 & Log_SalePrice<12.5))

ggplot(train_data,aes(x=GrLivArea,y=Log_SalePrice))+
  geom_point(color="darkblue",alpha=0.5)+
  geom_smooth(method = "lm",color = "red", se= FALSE)+
  theme_minimal()+
  labs(
    title = "Living Area vs. Log Sale Price (Outliers Removed)",
    subtitle = "The trend line is now much more accurate!",
    x = "Above Ground Living Area (Square Feet)",
    y = "Logarithm of Sale Price"
  )
```
```{r}
#اHouse price vs overall quality
ggplot(train_data,aes(x= factor(OverallQual), y= Log_SalePrice,fill =factor(OverallQual)))+
  geom_boxplot(alpha=0.5)+
  theme_minimal()+
  theme(legend.position = "none")+   # Hide the color legend since the X-axis already shows the numbers
  labs(
    title = "Effect of Overall Quality on House Price",
    subtitle = "staircase effect",
    x = "Overall Quality Score (1 = Poor, 10 = Excellent)",
    y = "Logarithm of Sale Price"
  )
  
  

```
```{r}
#finding 10 numeric features most correlated with Sale Price
#Select ONLY the columns that contain numbers

numeric_data<-train_data %>%
  select(where(is.numeric))
correlations<- cor(numeric_data,use = "complete.obs")[,"Log_SalePrice"]
cor_table<-data.frame(
  Feature= names(correlations),
  Correlation = as.numeric(correlations)
)%>%
  arrange(desc(Correlation))

head(cor_table,10)
```
```{r}
#feature engineering
train_data<- train_data %>%
  mutate(
    TotalArea = TotalBsmtSF +X1stFlrSF+X2ndFlrSF,
    HouseAge = YrSold - YearBuilt,
    TotalBath = FullBath +(0.5 * HalfBath) + BsmtFullBath +(0.5 * BsmtHalfBath)
  )
#checking correlation between total area and sales price
cor(train_data$TotalArea, train_data$Log_SalePrice, use = "complete.obs")
```
```{r}
model_data<-train_data %>%
  select(Log_SalePrice,OverallQual,TotalArea,GarageCars,HouseAge,TotalBath)%>%
  na.omit() #remove N/A
first_model <- lm(Log_SalePrice  ~.,data = model_data)
summary(first_model)#AI report
```

